docs/atas/ata1.md, docs/atas/ata2.md, mkdocs.yml
=> Atas reunioes

docs/elicitacao/perfil_de_usuario/perfil_de_usuario.md, docs/elicitacao/tecnicas/brainstorming/brainstorming.md, mkdocs.yml
=> Elicitacao/brainstorming/Perfil do usuário

docs/elicitacao/perfil_de_usuario/perfil_de_usuario.md, docs/elicitacao/tecnicas/brainstorming/brainstorming.md
=> Documento Final da técnica de Brainstorming

docs/elicitacao/perfil_de_usuario/perfil_de_usuario.md
=> Especificacao usuario

docs/elicitacao/perfil_de_usuario/perfil_de_usuario.md
=> editing graphics font

docs/elicitacao/perfil_de_usuario/perfil_de_usuario.md
=> Correction user profile

docs/elicitacao/tecnicas/brainstorming.md
=> Correção de cores e tabelas do brainstorming

docs/planejamento/cronograma.md
=> added release 2 executed schedule

.github/DOC_TEMPLATE.md, docs/atas/ata3.md, docs/atas/modelo-ata.md, mkdocs.yml
=> adicionando ata da reunião 3

docs/Apresentações/Apresentação_03.md
=> FIX Apresentação_03.md

docs/planejamento/cronograma.md
=> adicionando o executado da entrega 4

docs/modelagem/agil/historias_de_usuario.md, mkdocs.yml
=> Artefato apresentacao

docs/atas/ata5.md, docs/atas/modelo-ata.md, mkdocs.yml
=> adicionando ata 5

docs/verificacao/grupo+1/elicitacao/analise-documentos.md, docs/verificacao/grupo+1/elicitacao/brainstorming.md, docs/verificacao/grupo+1/elicitacao/firstThingsFirst.md, docs/verificacao/grupo+1/elicitacao/moscow.md
=> add revisores

docs/elicitacao/tecnicas/brainstorming.md, mkdocs.yml
=> Refatoração Requisitos Brainstorm

docs/elicitacao/tecnicas/brainstorming.md
=> Modificando tabelas do brainstorm

docs/elicitacao/tecnicas/analise-documental.md, docs/elicitacao/tecnicas/questionario.md, mkdocs.yml
=> Questionario

docs/planejamento/cronograma.md
=> Cronograma

docs/modelagem/especificacao_suplementar.md
=> Refatoração especificação suplementar.

docs/Apresentações/Apresentação_07.md, mkdocs.yml
=> add 5.2 presentation

docs/verificacao/grupo/elicitacao/tecnicas/quest.md, mkdocs.yml
=> Alterações Pablo

docs/entrega-final/Planejamento.md, docs/entrega-final/facilidades-dificuldades.md, docs/entrega-final/ferramentas.md, docs/entrega-final/sintese-verificacao/grupo3.md, docs/entrega-final/videos.md, mkdocs.yml
=> Entrega final
